CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    last_name text NOT NULL CHECK (last_name <> ''),
    e_mail text NOT NULL CHECK (e_mail <> ''),
    password text NOT NULL CHECK (password <> ''),
    phone TEXT NULL,
    postal_code INTEGER NULL,
    experience text NOT NULL CHECK (experience <> ''),
    token TEXT NULL
);

CREATE TABLE IF NOT EXISTS restaurants(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurant_name text NOT NULL CHECK (restaurant_name <> ''),
    address text NOT NULL CHECK (address <> ''),
    bussiness_name text NOT NULL CHECK (bussiness_name <> ''),
    rfc TEXT NOT NULL CHECK (rfc <> ''),
    postal_code INTEGER NULL,
    city TEXT NOT NULL CHECK (city <> ''),
    state TEXT NOT NULL CHECK (state <> ''),
    phone TEXT NULL,
    opening_time INTEGER NOT NULL,
    contact_name TEXT NOT NULL CHECK (contact_name <> '')
);

CREATE TABLE IF NOT EXISTS vacancies(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time INTEGER NULL,
    id_payment INTEGER, 
    benefits TEXT NOT NULL CHECK (benefits <> ''),
    validity_post INTEGER NOT NULL,
    restaurant_id integer REFERENCES restaurants(id)
);


